// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpiritAI.Database;

#nullable disable

namespace SpiritAI.Database.Migrations
{
    [DbContext(typeof(SpiritDbContext))]
    [Migration("20260911205837_Presence")]
    partial class Presence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("spirit")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpiritAI.Handoffs.Model.CallStub", b =>
                {
                    b.Property<string>("CallId")
                        .HasColumnType("text")
                        .HasColumnName("call_id");

                    b.HasKey("CallId");

                    b.ToTable("call", "public", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SpiritAI.Handoffs.Model.Handoff", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AskedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("asked_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("AskedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asked_by");

                    b.Property<string>("AssigneeKey")
                        .HasColumnType("text")
                        .HasColumnName("assignee_key");

                    b.Property<string>("AssigneeName")
                        .HasColumnType("text")
                        .HasColumnName("assignee_name");

                    b.Property<string>("CallId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("call_id");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<DateTimeOffset?>("DoneAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("done_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CallId")
                        .IsUnique()
                        .HasDatabaseName("handoff_open_per_call")
                        .HasFilter("status <> 'done'");

                    b.HasIndex("Status", "AskedAt")
                        .HasDatabaseName("handoff_queue");

                    b.ToTable("handoff", "spirit", t =>
                        {
                            t.HasCheckConstraint("handoff_asked_by_check", "asked_by IN ('bot', 'visitor')");

                            t.HasCheckConstraint("handoff_status_check", "status IN ('waiting', 'human', 'done')");
                        });
                });

            modelBuilder.Entity("SpiritAI.RealTime.Presence.Presence", b =>
                {
                    b.Property<string>("ConnectionId")
                        .HasColumnType("text")
                        .HasColumnName("connection_id");

                    b.Property<string>("CallerKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("caller_key");

                    b.Property<string>("CallerName")
                        .HasColumnType("text")
                        .HasColumnName("caller_name");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connected_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("SeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("seen_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ConnectionId");

                    b.HasIndex("Kind", "SeenAt")
                        .HasDatabaseName("presence_kind_seen_at");

                    b.ToTable("presence", "spirit");
                });

            modelBuilder.Entity("SpiritAI.Handoffs.Model.Handoff", b =>
                {
                    b.HasOne("SpiritAI.Handoffs.Model.CallStub", null)
                        .WithMany()
                        .HasForeignKey("CallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
