// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpiritAI.Database;

#nullable disable

namespace SpiritAI.Database.Migrations
{
    [DbContext(typeof(SpiritDbContext))]
    [Migration("20260924032533_HandoffPhone")]
    partial class HandoffPhone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("spirit")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpiritAI.Chatwoot.ChatwootLink", b =>
                {
                    b.Property<string>("ConversationId")
                        .HasColumnType("text")
                        .HasColumnName("conversation_id");

                    b.Property<long?>("AnnouncedHandoffId")
                        .HasColumnType("bigint")
                        .HasColumnName("announced_handoff_id");

                    b.Property<int>("ChatwootConversationId")
                        .HasColumnType("integer")
                        .HasColumnName("chatwoot_conversation_id");

                    b.Property<int>("CopiedThrough")
                        .HasColumnType("integer")
                        .HasColumnName("copied_through");

                    b.Property<string>("NotedPhone")
                        .HasColumnType("text")
                        .HasColumnName("noted_phone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ConversationId");

                    b.ToTable("chatwoot_link", "spirit");
                });

            modelBuilder.Entity("SpiritAI.Contacts.Contact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int?>("ChatwootContactId")
                        .HasColumnType("integer")
                        .HasColumnName("chatwoot_contact_id");

                    b.Property<string>("ChatwootSourceId")
                        .HasColumnType("text")
                        .HasColumnName("chatwoot_source_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.HasKey("Id");

                    b.ToTable("contact", "spirit");
                });

            modelBuilder.Entity("SpiritAI.Contacts.ContactConversation", b =>
                {
                    b.Property<string>("ConversationId")
                        .HasColumnType("text")
                        .HasColumnName("conversation_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<long>("ContactId")
                        .HasColumnType("bigint")
                        .HasColumnName("contact_id");

                    b.Property<int?>("NotedThrough")
                        .HasColumnType("integer")
                        .HasColumnName("noted_through");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ConversationId")
                        .HasName("PK_contact_conversation");

                    b.HasIndex("ContactId", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("contact_conversation_contact_id_started_at");

                    b.ToTable("contact_conversation", "spirit", t =>
                        {
                            t.HasCheckConstraint("contact_conversation_channel_check", "channel IN ('chat', 'phone')");
                        });
                });

            modelBuilder.Entity("SpiritAI.Contacts.ContactIdentity", b =>
                {
                    b.Property<string>("Kind")
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<long>("ContactId")
                        .HasColumnType("bigint")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.HasKey("Kind", "Value")
                        .HasName("PK_contact_identity");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("contact_identity_contact_id");

                    b.ToTable("contact_identity", "spirit", t =>
                        {
                            t.HasCheckConstraint("contact_identity_kind_check", "kind IN ('visitor', 'phone', 'email')");
                        });
                });

            modelBuilder.Entity("SpiritAI.Handoffs.Model.ConversationStub", b =>
                {
                    b.Property<string>("ConversationId")
                        .HasColumnType("text")
                        .HasColumnName("conversation_id");

                    b.HasKey("ConversationId");

                    b.ToTable("conversation", "agentcore", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SpiritAI.Handoffs.Model.Handoff", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AskedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("asked_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("AskedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asked_by");

                    b.Property<string>("AssigneeKey")
                        .HasColumnType("text")
                        .HasColumnName("assignee_key");

                    b.Property<string>("AssigneeName")
                        .HasColumnType("text")
                        .HasColumnName("assignee_name");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset?>("DoneAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("done_at");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .IsUnique()
                        .HasDatabaseName("handoff_open_per_conversation")
                        .HasFilter("status <> 'done'");

                    b.HasIndex("Status", "AskedAt")
                        .HasDatabaseName("handoff_queue");

                    b.ToTable("handoff", "spirit", t =>
                        {
                            t.HasCheckConstraint("handoff_asked_by_check", "asked_by IN ('bot', 'visitor')");

                            t.HasCheckConstraint("handoff_status_check", "status IN ('waiting', 'human', 'done')");
                        });
                });

            modelBuilder.Entity("SpiritAI.RealTime.Presence.Presence", b =>
                {
                    b.Property<string>("ConnectionId")
                        .HasColumnType("text")
                        .HasColumnName("connection_id");

                    b.Property<string>("CallerKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("caller_key");

                    b.Property<string>("CallerName")
                        .HasColumnType("text")
                        .HasColumnName("caller_name");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connected_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("SeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("seen_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ConnectionId");

                    b.HasIndex("Kind", "SeenAt")
                        .HasDatabaseName("presence_kind_seen_at");

                    b.ToTable("presence", "spirit");
                });

            modelBuilder.Entity("SpiritAI.Chatwoot.ChatwootLink", b =>
                {
                    b.HasOne("SpiritAI.Handoffs.Model.ConversationStub", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpiritAI.Contacts.ContactConversation", b =>
                {
                    b.HasOne("SpiritAI.Contacts.Contact", null)
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SpiritAI.Handoffs.Model.ConversationStub", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpiritAI.Contacts.ContactIdentity", b =>
                {
                    b.HasOne("SpiritAI.Contacts.Contact", null)
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SpiritAI.Handoffs.Model.Handoff", b =>
                {
                    b.HasOne("SpiritAI.Handoffs.Model.ConversationStub", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
