// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpiritAI.Database;

#nullable disable

namespace SpiritAI.Database.Migrations
{
    [DbContext(typeof(SpiritDbContext))]
    partial class SpiritDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("spirit")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpiritAI.Access.NeonUserStub", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("user", "neon_auth", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SpiritAI.Access.Role", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("AccessGroup")
                        .HasColumnType("text")
                        .HasColumnName("access_group");

                    b.HasKey("Name");

                    b.ToTable("role", "spirit", t =>
                        {
                            t.HasCheckConstraint("role_access_group_check", "access_group IN ('Guest', 'Dealer', 'TechService', 'InsideSales', 'InsideSalesSupervisor', 'TechServiceManager', 'InsideSalesManager', 'Admin')");
                        });
                });

            modelBuilder.Entity("SpiritAI.Access.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("UserId", "Role");

                    b.HasIndex("Role");

                    b.ToTable("user_role", "spirit");
                });

            modelBuilder.Entity("SpiritAI.Access.UserRole", b =>
                {
                    b.HasOne("SpiritAI.Access.Role", null)
                        .WithMany()
                        .HasForeignKey("Role")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SpiritAI.Access.NeonUserStub", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
