// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  ClaimHandoffData,
  ClaimHandoffErrors,
  ClaimHandoffResponses,
  CreateThreadData,
  CreateThreadErrors,
  CreateThreadResponses,
  DeleteThreadData,
  DeleteThreadErrors,
  DeleteThreadResponses,
  FinishHandoffData,
  FinishHandoffErrors,
  FinishHandoffResponses,
  GetHandoffData,
  GetHandoffErrors,
  GetHandoffMessagesData,
  GetHandoffMessagesErrors,
  GetHandoffMessagesResponses,
  GetHandoffResponses,
  GetOrderData,
  GetOrderErrors,
  GetOrderResponses,
  GetThreadData,
  GetThreadErrors,
  GetThreadMessagesData,
  GetThreadMessagesErrors,
  GetThreadMessagesResponses,
  GetThreadResponses,
  GetUnitData,
  GetUnitErrors,
  GetUnitResponses,
  ListHandoffsData,
  ListHandoffsErrors,
  ListHandoffsResponses,
  ListThreadsData,
  ListThreadsErrors,
  ListThreadsResponses,
  ReplyToHandoffData,
  ReplyToHandoffErrors,
  ReplyToHandoffResponses,
  UpdateThreadData,
  UpdateThreadErrors,
  UpdateThreadResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const listThreads = <ThrowOnError extends boolean = false>(
  options?: Options<ListThreadsData, ThrowOnError>,
): RequestResult<ListThreadsResponses, ListThreadsErrors, ThrowOnError> =>
  (options?.client ?? client).get<ListThreadsResponses, ListThreadsErrors, ThrowOnError>({
    url: "/v1/threads",
    ...options,
  });

export const createThread = <ThrowOnError extends boolean = false>(
  options?: Options<CreateThreadData, ThrowOnError>,
): RequestResult<CreateThreadResponses, CreateThreadErrors, ThrowOnError> =>
  (options?.client ?? client).post<CreateThreadResponses, CreateThreadErrors, ThrowOnError>({
    url: "/v1/threads",
    ...options,
  });

export const deleteThread = <ThrowOnError extends boolean = false>(
  options: Options<DeleteThreadData, ThrowOnError>,
): RequestResult<DeleteThreadResponses, DeleteThreadErrors, ThrowOnError> =>
  (options.client ?? client).delete<DeleteThreadResponses, DeleteThreadErrors, ThrowOnError>({
    url: "/v1/threads/{remoteId}",
    ...options,
  });

export const getThread = <ThrowOnError extends boolean = false>(
  options: Options<GetThreadData, ThrowOnError>,
): RequestResult<GetThreadResponses, GetThreadErrors, ThrowOnError> =>
  (options.client ?? client).get<GetThreadResponses, GetThreadErrors, ThrowOnError>({
    url: "/v1/threads/{remoteId}",
    ...options,
  });

export const updateThread = <ThrowOnError extends boolean = false>(
  options: Options<UpdateThreadData, ThrowOnError>,
): RequestResult<UpdateThreadResponses, UpdateThreadErrors, ThrowOnError> =>
  (options.client ?? client).patch<UpdateThreadResponses, UpdateThreadErrors, ThrowOnError>({
    url: "/v1/threads/{remoteId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const getThreadMessages = <ThrowOnError extends boolean = false>(
  options: Options<GetThreadMessagesData, ThrowOnError>,
): RequestResult<GetThreadMessagesResponses, GetThreadMessagesErrors, ThrowOnError> =>
  (options.client ?? client).get<GetThreadMessagesResponses, GetThreadMessagesErrors, ThrowOnError>(
    { url: "/v1/threads/{remoteId}/messages", ...options },
  );

export const getUnit = <ThrowOnError extends boolean = false>(
  options: Options<GetUnitData, ThrowOnError>,
): RequestResult<GetUnitResponses, GetUnitErrors, ThrowOnError> =>
  (options.client ?? client).get<GetUnitResponses, GetUnitErrors, ThrowOnError>({
    url: "/v1/units/{serial}",
    ...options,
  });

export const getOrder = <ThrowOnError extends boolean = false>(
  options: Options<GetOrderData, ThrowOnError>,
): RequestResult<GetOrderResponses, GetOrderErrors, ThrowOnError> =>
  (options.client ?? client).get<GetOrderResponses, GetOrderErrors, ThrowOnError>({
    url: "/v1/orders/{orderNumber}",
    ...options,
  });

export const listHandoffs = <ThrowOnError extends boolean = false>(
  options?: Options<ListHandoffsData, ThrowOnError>,
): RequestResult<ListHandoffsResponses, ListHandoffsErrors, ThrowOnError> =>
  (options?.client ?? client).get<ListHandoffsResponses, ListHandoffsErrors, ThrowOnError>({
    url: "/v1/handoff",
    ...options,
  });

export const getHandoff = <ThrowOnError extends boolean = false>(
  options: Options<GetHandoffData, ThrowOnError>,
): RequestResult<GetHandoffResponses, GetHandoffErrors, ThrowOnError> =>
  (options.client ?? client).get<GetHandoffResponses, GetHandoffErrors, ThrowOnError>({
    url: "/v1/handoff/{callId}",
    ...options,
  });

export const getHandoffMessages = <ThrowOnError extends boolean = false>(
  options: Options<GetHandoffMessagesData, ThrowOnError>,
): RequestResult<GetHandoffMessagesResponses, GetHandoffMessagesErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetHandoffMessagesResponses,
    GetHandoffMessagesErrors,
    ThrowOnError
  >({ url: "/v1/handoff/{callId}/messages", ...options });

export const replyToHandoff = <ThrowOnError extends boolean = false>(
  options: Options<ReplyToHandoffData, ThrowOnError>,
): RequestResult<ReplyToHandoffResponses, ReplyToHandoffErrors, ThrowOnError> =>
  (options.client ?? client).post<ReplyToHandoffResponses, ReplyToHandoffErrors, ThrowOnError>({
    url: "/v1/handoff/{callId}/messages",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const claimHandoff = <ThrowOnError extends boolean = false>(
  options: Options<ClaimHandoffData, ThrowOnError>,
): RequestResult<ClaimHandoffResponses, ClaimHandoffErrors, ThrowOnError> =>
  (options.client ?? client).post<ClaimHandoffResponses, ClaimHandoffErrors, ThrowOnError>({
    url: "/v1/handoff/{callId}/claim",
    ...options,
  });

export const finishHandoff = <ThrowOnError extends boolean = false>(
  options: Options<FinishHandoffData, ThrowOnError>,
): RequestResult<FinishHandoffResponses, FinishHandoffErrors, ThrowOnError> =>
  (options.client ?? client).post<FinishHandoffResponses, FinishHandoffErrors, ThrowOnError>({
    url: "/v1/handoff/{callId}/done",
    ...options,
  });
