// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost/" | (string & {});
};

export type HandoffAssignee = {
  key: string;
  name: string;
};

export type HandoffMessage = {
  callId: string;
  messageId: string;
  role: string;
  text: string;
  speaker: null | HandoffSpeaker;
  at: string;
};

export type HandoffPage = {
  items: Array<HandoffSummary>;
};

export type HandoffReplyRequest = {
  text: string;
};

export type HandoffSpeaker = {
  kind: string;
  name: string;
  detail: null | string;
};

export type HandoffSummary = {
  id: number;
  callId: string;
  status: string;
  askedBy: string;
  reason: null | string;
  askedAt: string;
  assignee: null | HandoffAssignee;
  claimedAt: null | string;
  email: null | string;
  doneAt: null | string;
  title: null | string;
  firstLine: null | string;
  position: null | number;
};

export type JobStatus = "open" | "closed" | "unknown";

export type JsonElement = unknown;

export type OrderDocument = {
  orderNumber: string;
  serviceId: number;
  orderId: null | number;
  orderType: null | string;
  orderedOn: null | string;
  appointedOn: null | string;
  shippedOn: null | string;
  closedOn: null | string;
  technician: null | string;
  ispName: null | string;
  ispStatus: null | string;
  dealerNo: null | string;
  trackingNo: null | string;
  notes: null | string;
  lines: Array<OrderLine>;
};

export type OrderLine = {
  partNo: null | string;
  description: null | string;
  shipped: null | number;
  isReturned: boolean;
};

export type ProblemDetails = {
  type?: null | string;
  title?: null | string;
  status?: null | number;
  detail?: null | string;
  instance?: null | string;
};

export type ThreadCreated = {
  remoteId: string;
  externalId: null | string;
};

export type ThreadHistory = {
  headId: null | string;
  messages: Array<ThreadHistoryItem>;
};

export type ThreadHistoryItem = {
  parentId: null | string;
  message: ThreadHistoryMessage;
};

export type ThreadHistoryMessage = {
  id: string;
  role: string;
  content: Array<ThreadPart>;
  createdAt: string;
  metadata: ThreadMessageMetadata;
  status?: null | ThreadMessageStatus;
  attachments?: null | Array<unknown>;
};

export type ThreadMessageMetadata = {
  custom?: {
    [key: string]: unknown;
  };
};

export type ThreadMessageStatus = {
  type: string;
};

export type ThreadPage = {
  threads: Array<ThreadSummary>;
  nextCursor: null | string;
};

export type ThreadPart =
  | ({
      type: "text";
    } & ThreadPartThreadTextPart)
  | ({
      type: "tool-call";
    } & ThreadPartThreadToolCallPart)
  | ({
      type: "source";
    } & ThreadPartThreadSourcePart)
  | ({
      type: "data";
    } & ThreadPartThreadDataPart);

export type ThreadPartThreadDataPart = {
  type?: "data";
  name: string;
  data: JsonElement;
};

export type ThreadPartThreadSourcePart = {
  type?: "source";
  id: string;
  sourceType: string;
  title: string;
  url: null | string;
  mediaType: string;
  parentId: string;
  providerMetadata: ThreadSourceMetadata;
};

export type ThreadPartThreadTextPart = {
  type?: "text";
  text: string;
};

export type ThreadPartThreadToolCallPart = {
  type?: "tool-call";
  toolCallId: string;
  toolName: string;
  args: JsonElement;
  argsText: string;
  result?: null | JsonElement;
  isError?: null | boolean;
};

export type ThreadSourceMetadata = {
  agentcore: ThreadSourceOrigin;
};

export type ThreadSourceOrigin = {
  origin: string;
  locator: string;
};

export type ThreadStatus = "regular" | "archived";

export type ThreadSummary = {
  remoteId: string;
  status: ThreadStatus;
  externalId: null | string;
  title: null | string;
  lastMessageAt: null | string;
  custom: null | {
    [key: string]: unknown;
  };
};

export type UnitDocument = {
  serial: string;
  header: null | UnitHeader;
  jobs: null | Array<UnitJob>;
  history: null | Array<UnitJob>;
  parts: null | Array<UnitPart>;
  warranty: null | Array<WarrantyTerm>;
  unavailable: Array<UnitSection>;
};

export type UnitHeader = {
  serial: string;
  modelNo: string;
  modelVersion: null | number;
  modelName: null | string;
  category: null | string;
  isSole: boolean;
  manufacturedOn: null | string;
  purchasedOn: null | string;
  setUpOn: null | string;
};

export type UnitJob = {
  orderNumber: string;
  serviceId: number;
  orderId: null | number;
  status: JobStatus;
  statusText: null | string;
  calledOn: null | string;
  servicedOn: null | string;
  technician: null | string;
  summary: null | string;
  solution: null | string;
};

export type UnitPart = {
  spNo: string;
  dyacoNo: null | string;
  description: null | string;
  quantity: null | number;
};

export type UnitSection = "header" | "jobs" | "history" | "parts" | "warranty";

export type WarrantyTerm = {
  category: string;
  days: number;
  expiresOn: null | string;
  isCovered: null | boolean;
};

export type ListThreadsData = {
  body?: never;
  path?: never;
  query?: {
    after?: string;
    limit?: number;
    status?: string;
  };
  url: "/v1/threads";
};

export type ListThreadsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
};

export type ListThreadsError = ListThreadsErrors[keyof ListThreadsErrors];

export type ListThreadsResponses = {
  /**
   * OK
   */
  200: ThreadPage;
};

export type ListThreadsResponse = ListThreadsResponses[keyof ListThreadsResponses];

export type CreateThreadData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/threads";
};

export type CreateThreadErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type CreateThreadResponses = {
  /**
   * Created
   */
  201: ThreadCreated;
};

export type CreateThreadResponse = CreateThreadResponses[keyof CreateThreadResponses];

export type DeleteThreadData = {
  body?: never;
  path: {
    remoteId: string;
  };
  query?: never;
  url: "/v1/threads/{remoteId}";
};

export type DeleteThreadErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Not Found
   */
  404: unknown;
};

export type DeleteThreadResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteThreadResponse = DeleteThreadResponses[keyof DeleteThreadResponses];

export type GetThreadData = {
  body?: never;
  path: {
    remoteId: string;
  };
  query?: never;
  url: "/v1/threads/{remoteId}";
};

export type GetThreadErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Not Found
   */
  404: unknown;
};

export type GetThreadResponses = {
  /**
   * OK
   */
  200: ThreadSummary;
};

export type GetThreadResponse = GetThreadResponses[keyof GetThreadResponses];

export type UpdateThreadData = {
  body: JsonElement;
  path: {
    remoteId: string;
  };
  query?: never;
  url: "/v1/threads/{remoteId}";
};

export type UpdateThreadErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Not Found
   */
  404: unknown;
};

export type UpdateThreadError = UpdateThreadErrors[keyof UpdateThreadErrors];

export type UpdateThreadResponses = {
  /**
   * No Content
   */
  204: void;
};

export type UpdateThreadResponse = UpdateThreadResponses[keyof UpdateThreadResponses];

export type GetThreadMessagesData = {
  body?: never;
  path: {
    remoteId: string;
  };
  query?: never;
  url: "/v1/threads/{remoteId}/messages";
};

export type GetThreadMessagesErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Not Found
   */
  404: unknown;
};

export type GetThreadMessagesResponses = {
  /**
   * OK
   */
  200: ThreadHistory;
};

export type GetThreadMessagesResponse =
  GetThreadMessagesResponses[keyof GetThreadMessagesResponses];

export type GetUnitData = {
  body?: never;
  path: {
    serial: string;
  };
  query?: never;
  url: "/v1/units/{serial}";
};

export type GetUnitErrors = {
  /**
   * Not Found
   */
  404: unknown;
};

export type GetUnitResponses = {
  /**
   * OK
   */
  200: UnitDocument;
};

export type GetUnitResponse = GetUnitResponses[keyof GetUnitResponses];

export type GetOrderData = {
  body?: never;
  path: {
    orderNumber: string;
  };
  query?: never;
  url: "/v1/orders/{orderNumber}";
};

export type GetOrderErrors = {
  /**
   * Not Found
   */
  404: unknown;
};

export type GetOrderResponses = {
  /**
   * OK
   */
  200: OrderDocument;
};

export type GetOrderResponse = GetOrderResponses[keyof GetOrderResponses];

export type ListHandoffsData = {
  body?: never;
  path?: never;
  query?: {
    status?: string;
    limit?: number;
  };
  url: "/v1/handoff";
};

export type ListHandoffsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: ProblemDetails;
};

export type ListHandoffsError = ListHandoffsErrors[keyof ListHandoffsErrors];

export type ListHandoffsResponses = {
  /**
   * OK
   */
  200: HandoffPage;
};

export type ListHandoffsResponse = ListHandoffsResponses[keyof ListHandoffsResponses];

export type GetHandoffData = {
  body?: never;
  path: {
    callId: string;
  };
  query?: never;
  url: "/v1/handoff/{callId}";
};

export type GetHandoffErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: ProblemDetails;
  /**
   * Not Found
   */
  404: unknown;
};

export type GetHandoffError = GetHandoffErrors[keyof GetHandoffErrors];

export type GetHandoffResponses = {
  /**
   * OK
   */
  200: HandoffSummary;
};

export type GetHandoffResponse = GetHandoffResponses[keyof GetHandoffResponses];

export type GetHandoffMessagesData = {
  body?: never;
  path: {
    callId: string;
  };
  query?: never;
  url: "/v1/handoff/{callId}/messages";
};

export type GetHandoffMessagesErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: ProblemDetails;
  /**
   * Not Found
   */
  404: unknown;
};

export type GetHandoffMessagesError = GetHandoffMessagesErrors[keyof GetHandoffMessagesErrors];

export type GetHandoffMessagesResponses = {
  /**
   * OK
   */
  200: ThreadHistory;
};

export type GetHandoffMessagesResponse =
  GetHandoffMessagesResponses[keyof GetHandoffMessagesResponses];

export type ReplyToHandoffData = {
  body?: null | HandoffReplyRequest;
  path: {
    callId: string;
  };
  query?: never;
  url: "/v1/handoff/{callId}/messages";
};

export type ReplyToHandoffErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: ProblemDetails;
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type ReplyToHandoffError = ReplyToHandoffErrors[keyof ReplyToHandoffErrors];

export type ReplyToHandoffResponses = {
  /**
   * Created
   */
  201: HandoffMessage;
};

export type ReplyToHandoffResponse = ReplyToHandoffResponses[keyof ReplyToHandoffResponses];

export type ClaimHandoffData = {
  body?: never;
  path: {
    callId: string;
  };
  query?: never;
  url: "/v1/handoff/{callId}/claim";
};

export type ClaimHandoffErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: ProblemDetails;
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type ClaimHandoffError = ClaimHandoffErrors[keyof ClaimHandoffErrors];

export type ClaimHandoffResponses = {
  /**
   * OK
   */
  200: HandoffSummary;
};

export type ClaimHandoffResponse = ClaimHandoffResponses[keyof ClaimHandoffResponses];

export type FinishHandoffData = {
  body?: never;
  path: {
    callId: string;
  };
  query?: never;
  url: "/v1/handoff/{callId}/done";
};

export type FinishHandoffErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: ProblemDetails;
  /**
   * Not Found
   */
  404: unknown;
};

export type FinishHandoffError = FinishHandoffErrors[keyof FinishHandoffErrors];

export type FinishHandoffResponses = {
  /**
   * No Content
   */
  204: void;
};

export type FinishHandoffResponse = FinishHandoffResponses[keyof FinishHandoffResponses];
